### ISSUE TITLE
cat command crashes bot once in a tiny while

### ISSUE THREAD

**Issue by kevinzwang** [kevinzwang/marvin-go#1]
```
panic: runtime error: slice bounds out of range

goroutine 158 [running]:
panic(0x880ec0, 0xc82000a0c0)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
_/home/randomnumber17/marvin-go/commands.(*Cat).execute(0xb900c8, 0xc820354800, 0xc820353c60, 0x0, 0x0)
        /home/randomnumber17/marvin-go/commands/cat.go:24 +0x2a8
created by _/home/randomnumber17/marvin-go/commands.Handle
        /home/randomnumber17/marvin-go/commands/commandutils.go:126 +0x5ac
```

I should rewrite the !cat command with actual html libs instead of this janky shit

**Comment by kevinzwang** [comment]
changed to random.cat api
