### ISSUE TITLE
using avatar command in DM crashes bot

### ISSUE THREAD

**Issue by kevinzwang** [kevinzwang/marvin-go#3]
When you try that, this occurs:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x48227f]

goroutine 65067 [running]:
panic(0x88bc20, 0xc82000a100)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
_/home/randomnumber17/marvin-go/commands.(*Avatar).getID(0xba5120, 0xc8202e5e90,
 0xc8202f1b90, 0x1, 0x1, 0x0, 0x0, 0xc82001dfa0)
        /home/randomnumber17/marvin-go/commands/avatar.go:42 +0x45f
_/home/randomnumber17/marvin-go/commands.(*Avatar).execute(0xba5120, 0xc8202e5e9
0, 0xc8202f1b90, 0x1, 0x1)
        /home/randomnumber17/marvin-go/commands/avatar.go:13 +0x67
created by _/home/randomnumber17/marvin-go/commands.Handle
        /home/randomnumber17/marvin-go/commands/commandutils.go:152 +0x76b
Makefile:6: recipe for target 'run' failed
make: *** [run] Error 2
```

I suspect it's because the bot searches the server, and since a DM is not a server, it tries to access something that's not there and panics.

**Comment by kevinzwang** [comment]
fixed
